###
GET http://localhost:5000/api/rooms


###
POST http://localhost:5000/api/rooms
Content-Type: application/json

{
    "name": "test room 6",
    "price": 500,
    "desc": "some description",
    "roomNumbers": [{
        "number": 101,
        "unavailableDates": ["2024-10-26", "2024-10-28"]
    }]
}

#get single room
###
GET http://localhost:5000/api/rooms/67205d83c0d385e542191c44

#updated room
###
PUT http://localhost:5000/api/rooms/67205d83c0d385e542191c44
Content-Type: application/json

{
    "name": "test room 3",
    "price": 12300,
    "desc": "Sua",
    "roomNumbers": [{
        "number": 99,
        "unavailableDates": ["2024-10-25", "2024-10-24"]
    }]
}

#delte room
###

DELETE http://localhost:5000/api/rooms/67205d83c0d385e542191c44

#--------------------------------------------
##Get bookings
###
GET http://localhost:5000/api/bookings

#Create booking
###
POST http://localhost:5000/api/bookings
Content-Type: application/json

{
    "roomId": "671cc69beccdb76fea998cb9",
    "name": "Msbreezce",
    "email": "Msbreezce@gmail.com",
    "checkInDate": "2024-10-24", 
    "checkOutDate": "2024-10-25" 
}

#update boking
###
PUT http://localhost:5000/api/bookings/67205dfac0d385e542191c64
Content-Type: application/json

{
    "name": "Thien",
    "email": "thien@gmail.com"
}

#delete boking
###
DELETE http://localhost:5000/api/bookings/671cda1e4d19795014d93e64

##Get single booking
###
GET http://localhost:5000/api/bookings/67205e7cc0d385e542191c6f

//
#create users 
### 
POST http://localhost:5000/api/users 
Content-Type: application/json

{
"name": "Hekki", "email": "123@gmail.com", "password": "123"
}

#login user 
### 
POST http://localhost:5000/api/users/login 
Content-Type: application/json

{
"email": "123@gmail.com", "password": "123"
}

#logout user 
### 
GET http://localhost:5000/api/users/logout

#------------------- 
#check auth
### 
GET http://localhost:5000/auth